server:
  port: 9111

spring:
  datasource:
    url: jdbc:mysql://rm-bp1v216o7sx3s41vhbo.mysql.rds.aliyuncs.com:3306/dsh_database
    username: yuanxin
    password: 99kingyuan@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


img:
  upload-dir: /Users/tornado/Downloads/test
  mapper-path: http://10.147.160.28:9111/goods_img/

#img:
#  upload-dir: /home/webapp/2hand Api/data/images/
#  mapper-path: http://101.35.135.139:9111/goods_img/

page:
  page-size: 10

#pagehelper:
#  # dialect: ①
#  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
#  helper-dialect: mysql
#  # 上面数据库设置后，下面的设置为true不会改变上面的结果（默认为true）
#  auto-dialect: true
#  page-size-zero: false # ②
#  reasonable: true # ③
#  # 默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。（一般用不着）
#  offset-as-page-num: false
#  # 默认值为 false，RowBounds是否进行count查询（一般用不着）
#  row-bounds-with-count: false
#  #params: ④
#  #support-methods-arguments: 和params配合使用，具体可以看下面的讲解
#  # 默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页
#  auto-runtime-dialect: false # ⑤
#  # 与auto-runtime-dialect配合使用
#  close-conn: true
#  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
#  default-count: false
#  #dialect-alias: ⑥
